"""Run the raw OULAD data audit and validation stage."""

from __future__ import annotations

import argparse
from datetime import date
import logging
from pathlib import Path
import sys
from typing import Sequence

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from oulad_causal.config import ProjectPaths
from oulad_causal.io import OULAD_TABLE_SPECS, load_oulad_tables, locate_oulad_tables, resolve_raw_source
from oulad_causal.logging_utils import add_log_level_argument, configure_logging
from oulad_causal.validation import validate_oulad_raw_data, write_validation_artifacts


LOGGER = logging.getLogger(__name__)
GENERATED_AUDIT_START = "<!-- BEGIN GENERATED DATA AUDIT -->"
GENERATED_AUDIT_END = "<!-- END GENERATED DATA AUDIT -->"
GENERATED_DECISION_START = "<!-- BEGIN GENERATED DATA VALIDATION DECISION -->"
GENERATED_DECISION_END = "<!-- END GENERATED DATA VALIDATION DECISION -->"


def main(argv: Sequence[str] | None = None) -> int:
    """Run data validation, write metadata artifacts, and refresh audit docs."""

    args = parse_args(argv)
    configure_logging(args.log_level)
    paths = ProjectPaths.from_overrides(
        raw_data_dir=args.raw_data_dir,
        metadata_dir=args.metadata_dir,
        docs_dir=args.docs_dir,
    )
    raw_source = _resolve_optional_path(args.raw_source)

    locations = locate_oulad_tables(raw_source=raw_source, raw_data_dir=paths.raw_data_dir)
    tables = load_oulad_tables(raw_source=raw_source, raw_data_dir=paths.raw_data_dir)
    result = validate_oulad_raw_data(tables, locations)

    write_validation_artifacts(result, paths.metadata_dir)
    refresh_data_dictionary(paths.docs_dir / "data_dictionary.md", result)
    refresh_decisions_log(paths.docs_dir / "decisions_log.md", result, raw_source, paths.raw_data_dir)

    LOGGER.info("Wrote validation metadata to %s", paths.metadata_dir)
    LOGGER.info("Updated %s", paths.docs_dir / "data_dictionary.md")
    LOGGER.info("Updated %s", paths.docs_dir / "decisions_log.md")
    if result.critical_failures:
        LOGGER.error("Critical validation failures:")
        for failure in result.critical_failures:
            LOGGER.error("- %s", failure)

    if args.strict and result.critical_failures:
        return 1
    return 0


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw-source", help="Explicit OULAD archive or extracted CSV directory.")
    parser.add_argument("--raw-data-dir", help="Raw data directory. Defaults to data/raw or OULAD_RAW_DATA_DIR.")
    parser.add_argument("--metadata-dir", help="Directory for validation metadata outputs.")
    parser.add_argument("--docs-dir", help="Directory containing data_dictionary.md and decisions_log.md.")
    parser.add_argument(
        "--strict",
        dest="strict",
        action="store_true",
        default=True,
        help="Exit nonzero when critical validation failures are found. This is the default.",
    )
    parser.add_argument(
        "--non-strict",
        dest="strict",
        action="store_false",
        help="Write outputs but exit zero even when critical validation failures are found.",
    )
    add_log_level_argument(parser)
    return parser.parse_args(argv)


def refresh_data_dictionary(path: Path, result) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text() if path.exists() else "# Data Dictionary\n"
    generated = build_data_dictionary_section(result)
    path.write_text(_replace_managed_section(existing, generated, GENERATED_AUDIT_START, GENERATED_AUDIT_END))


def refresh_decisions_log(path: Path, result, raw_source: Path | None, raw_data_dir: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text() if path.exists() else "# Decisions Log\n"
    generated = build_decisions_section(result, raw_source, raw_data_dir)
    path.write_text(_replace_managed_section(existing, generated, GENERATED_DECISION_START, GENERATED_DECISION_END))


def build_data_dictionary_section(result) -> str:
    today = date.today().isoformat()
    shapes = result.summaries["table_shapes"]
    schema = result.summaries["schema_validation"]
    duplicates = result.summaries["duplicate_key_summary"]
    dates = result.summaries["date_range_summary"]

    lines = [
        GENERATED_AUDIT_START,
        "",
        "## Generated Raw OULAD Data Audit",
        "",
        f"Generated by `scripts/run_data_validation.py` on {today}. This section is based on saved validation metadata, not manual notebook state.",
        "",
        "### Raw Tables",
        "",
        _markdown_table(
            shapes[["table_name", "loaded", "row_count", "column_count", "expected_column_count"]].to_dict("records"),
            ["table_name", "loaded", "row_count", "column_count", "expected_column_count"],
        ),
        "",
        "### Standard OULAD Fields",
        "",
        _markdown_table(
            [
                {
                    "table_name": spec.name,
                    "filename": spec.filename,
                    "expected_columns": ", ".join(spec.columns),
                }
                for spec in OULAD_TABLE_SPECS.values()
            ],
            ["table_name", "filename", "expected_columns"],
        ),
        "",
        "### Schema Status",
        "",
        _markdown_table(
            schema[["table_name", "loaded", "missing_columns", "extra_columns", "column_order_matches", "is_valid"]].to_dict("records"),
            ["table_name", "loaded", "missing_columns", "extra_columns", "column_order_matches", "is_valid"],
        ),
        "",
        "### Duplicate-Key Status",
        "",
        _markdown_table(
            duplicates[["table_name", "key_columns", "checked", "duplicate_rows", "duplicate_groups", "status"]].to_dict("records"),
            ["table_name", "key_columns", "checked", "duplicate_rows", "duplicate_groups", "status"],
        ),
        "",
        "### Date-Range Sanity Status",
        "",
        _markdown_table(
            dates[["table_name", "column", "missing_count", "nonnumeric_count", "min", "max", "warning"]].to_dict("records"),
            ["table_name", "column", "missing_count", "nonnumeric_count", "min", "max", "warning"],
        ),
        "",
        "Full missingness and category-frequency summaries are saved under `data/metadata/`.",
        "",
        GENERATED_AUDIT_END,
        "",
    ]
    return "\n".join(lines)


def build_decisions_section(result, raw_source: Path | None, raw_data_dir: Path) -> str:
    today = date.today().isoformat()
    resolved_source = raw_source or resolve_raw_source(raw_data_dir=raw_data_dir)
    status = "passed" if result.passed else "reported critical validation failures"
    lines = [
        GENERATED_DECISION_START,
        "",
        f"## {today} Generated Data Validation Decision",
        "",
        f"- Ran the deterministic raw OULAD validation stage against `{resolved_source}`.",
        "- Treated the seven standard OULAD CSV files as the required raw ingestion surface.",
        "- Required exact standard column names and reported mismatches rather than renaming columns.",
        "- Checked duplicate keys only for tables with expected one-row-per-key structure; `studentVle` repeated activity rows were summarized but not treated as duplicate-key failures.",
        "- Wrote validation metadata to `data/metadata/` and refreshed the generated data audit in `docs/data_dictionary.md`.",
        "- Did not start cohort construction, treatment definition, outcome coding, or causal adjustment.",
        f"- Validation status: {status}.",
        "",
        GENERATED_DECISION_END,
        "",
    ]
    return "\n".join(lines)


def _replace_managed_section(existing: str, generated: str, start: str, end: str) -> str:
    if start in existing and end in existing:
        before = existing.split(start, 1)[0].rstrip()
        after = existing.split(end, 1)[1].lstrip()
        pieces = [before, generated.rstrip(), after.rstrip()]
        return "\n\n".join(piece for piece in pieces if piece) + "\n"
    return existing.rstrip() + "\n\n" + generated


def _markdown_table(rows: list[dict[str, object]], columns: list[str]) -> str:
    if not rows:
        rows = [{column: "" for column in columns}]
    header = "| " + " | ".join(columns) + " |"
    divider = "| " + " | ".join("---" for _ in columns) + " |"
    body = [
        "| " + " | ".join(_markdown_cell(row.get(column, "")) for column in columns) + " |"
        for row in rows
    ]
    return "\n".join([header, divider, *body])


def _markdown_cell(value: object) -> str:
    if value is None:
        return ""
    return str(value).replace("|", "\\|").replace("\n", " ")


def _resolve_optional_path(value: str | None) -> Path | None:
    if value is None:
        return None
    return Path(value).expanduser().resolve()


if __name__ == "__main__":
    raise SystemExit(main())
